DROP TABLE IF EXISTS SchoolData.Students;
DROP TABLE IF EXISTS SchoolData.Schools;
DROP TABLE IF EXISTS SchoolData.SchoolStudents;
DROP TABLE IF EXISTS SchoolData.Roles;
DROP TABLE IF EXISTS SchoolData.TeamRoles;
DROP TABLE IF EXISTS SchoolData.TeamUsers;
DROP TABLE IF EXISTS SchoolData.Teams;
DROP TABLE IF EXISTS SchoolData.UserRoles;
DROP TABLE IF EXISTS SchoolData.Users;

DROP SCHEMA IF EXISTS SchoolData;
DROP SCHEMA IF EXISTS Security;
