DROP TABLE IF EXISTS Student;
DROP TABLE IF EXISTS School;
DROP TABLE IF EXISTS SchoolStudent;
DROP TABLE IF EXISTS Roles;
DROP TABLE IF EXISTS TeamRoles;
DROP TABLE IF EXISTS TeamUsers;
DROP TABLE IF EXISTS Teams;
DROP TABLE IF EXISTS UserRoles;
DROP TABLE IF EXISTS Users;

DROP SCHEMA IF EXISTS SchoolData
DROP SCHEMA IF EXISTS Security
